### ISSUE TITLE
Fail to login

### ISSUE THREAD

**Issue by Keeboy99** [AlecJY/TaikoWebSongImportTool#4]
Hi when trying to run the tool I always get this error

Dec 17, 2023 7:00:02 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: session=8e653ef2-d88c-4c38-bd94-63e99ebaacfe; Expires=Wed, 17 Jan 2024 07:00:02 GMT; HttpOnly; Path=/". Invalid 'expires' attribute: Wed, 17 Jan 2024 07:00:02 GMT
Dec 17, 2023 7:00:02 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: session=21ceb298-add6-475c-865f-abda5d95b2db; Expires=Wed, 17 Jan 2024 07:00:02 GMT; HttpOnly; Path=/". Invalid 'expires' attribute: Wed, 17 Jan 2024 07:00:02 GMT
Fail to login
java.lang.Exception: Login error
        at com.alebit.taikoweb.TaikoWeb.<init>(TaikoWeb.kt:40)
        at com.alebit.taikoweb.MainKt.main(Main.kt:21)
        
I have checked multiple times that the username and password is correct but the error always happens

**Comment by AlecJY** [comment]
I've pushed a commit to fix this bug. Please give it another try.

**Comment by Keeboy99** [comment]
> I've pushed a commit to fix this bug. Please give it another try.

Hi I am trying to build the new version I am using java 19 and I got this error while trying to build

* What went wrong:
Execution failed for task ':fatJar'.
Entry META-INF/versions/9/module-info.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.5/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

EDIT I got it working I just changed some stuff in the build.gradle

also I was wondering if it was possible for you to make this program work with box.def files

**Comment by AlecJY** [comment]
The Gradle fatJar task bug has been fixed, and it seems that adding support for the box.def file is not too complex. Therefore, I've implemented a simple box.def parser to support it.
