### ISSUE TITLE
Broke Taiko Web

### ISSUE THREAD

**Issue by Keeboy99** [AlecJY/TaikoWebSongImportTool#5]
after I used it to add one song and that worked fine but when I used it to add around 40 songs taiko web just broke whenever I try going to taiko web I get this error

```
/api/songs (500): /api/songs
/api/songs (500)
Percentage: 76%
```

**Comment by AlecJY** [comment]
I'm uncertain whether this bug is caused by taiko-web itself or my tool. The status code 500 indicated a server side issue. Please check that if there are some error messages in your server's output to provide more information for debugging.

**Comment by Keeboy99** [comment]
My full error log

[2023-12-18 17:06:42 +0000] [14136] [INFO] Starting gunicorn 20.0.4
[2023-12-18 17:06:42 +0000] [14136] [INFO] Listening at: http://127.0.0.1:34801 (14136)
[2023-12-18 17:06:42 +0000] [14136] [INFO] Using worker: sync
[2023-12-18 17:06:42 +0000] [14139] [INFO] Booting worker with pid: 14139
[2023-12-18 17:07:03,568] ERROR in app: Exception on /api/songs [GET]
Traceback (most recent call last):
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 459, in decorated_function
    rv = f(*args, **kwargs)
  File "/srv/taiko-web/app.py", line 450, in route_api_songs
    song['category'] = db.categories.find_one({'id': song['category_id']})['title']
TypeError: 'NoneType' object is not subscriptable
[2023-12-18 17:07:10,745] ERROR in app: Exception on /api/songs [GET]
Traceback (most recent call last):
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/taiko-web/.venv/lib/python3.10/site-packages/flask_caching/__init__.py", line 459, in decorated_function
    rv = f(*args, **kwargs)
  File "/srv/taiko-web/app.py", line 450, in route_api_songs
    song['category'] = db.categories.find_one({'id': song['category_id']})['title']
TypeError: 'NoneType' object is not subscriptable

**Comment by AlecJY** [comment]
Please give me the contents in http://localhost/api/categories. Remember to replace localhost with your server's IP address and port.

**Comment by Keeboy99** [comment]
its just blank

[]

**Comment by AlecJY** [comment]
It looks like the song categories data didn't import into MongoDB.

Run the command
```bash
mongoimport --db taiko --collection categories --file /srv/taiko-web/tools/categories.json --jsonArray
```

**Comment by Keeboy99** [comment]
Thanks for the help I must have just forgotten to do that when setting up
